#!/bin/bash

# 服务名
SERVICE_NAME="s3ip-sysfs.service"

# 等待服务启动成功
while true; do
    # 检查服务状态是否为active (running)
    STATUS=$(systemctl is-active $SERVICE_NAME)
    
    if [ "$STATUS" = "active" ]; then
        echo "$SERVICE_NAME 已成功启动"
        break
    else
        echo "$SERVICE_NAME 未启动，等待中..."
        sleep 5  # 每隔5秒检查一次
    fi
done

# 服务启动成功后执行后续命令
echo "执行后续操作..."
# 在这里写入你需要执行的命令



TARGET_DIR="/sys/bus/i2c/devices/i2c-213"

# 持续检查文件夹是否存在
while [ ! -d "$TARGET_DIR" ]; do
    echo "等待 $TARGET_DIR 创建..."
    sleep 1  # 等待 1 秒后继续检查
done
