obj-m:= baotuspring_i2c_mux_pca954x.o \
		qianfomountain_i2c_ocores_tiger.o \
		qianfomountain_lpc_platform.o \
		baotuspring_i2c_i801.o \
		daminglake_fpga_ocores.o \
		daminglake_fpga_sff_rtc.o

baotuspring_i2c_i801-objs := i2c-i801.o
baotuspring_i2c_mux_pca954x-objs := i2c-mux-pca954x.o
qianfomountain_lpc_platform-objs := lpc_platform.o
qianfomountain_i2c_ocores_tiger-objs := i2c_ocores_tiger.o
ccflags-y := -I$(M)/include -Wall -Wextra -Wno-unused-parameter
